### Find All Content
GET http://localhost:8080/api/content

### Get Content by ID
GET http://localhost:8080/api/content/1

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "Drugi POST",
  "desc": "Drugi opis",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-03-13T18:47:22.4775373",
  "dateUpdated": null,
  "url": ""
}

### Update existing Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "DRUGI POST!",
  "desc": "DRUGI OPIS!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-03-13T18:47:22.4775373",
  "dateUpdated": null,
  "url": "http://localhost:8080/pierwszy-post"
}